version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - trivia-network

  backend:
    build:
      context: ./server
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - HOST=db
      - USERNAME=alex
      - PASSWORD=password
      - PORT=5432
      - DNAME=trivia_game
      - JWT_SECRET=xpwGXFeGVRntC5nj1CTkOlSFGIabkilU6kSGeFN-Rt8=
    networks:
      - trivia-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trivia_game
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trivia-network

networks:
  trivia-network:

volumes:
  db-data:
