INSERT INTO questions (question_text, correct_answer, wrong_answers) VALUES 
('What is the smallest planet in our solar system?', 'Mercury', '{"Venus", "Mars", "Earth"}'),
('Who is the author of the Harry Potter series?', 'J.K. Rowling', '{"Stephen King", "J.R.R. Tolkien", "George R.R. Martin"}'),
('What is the currency of Japan?', 'Yen', '{"Won", "Dollar", "Euro"}'),
('Which country is known as the Land of the Rising Sun?', 'Japan', '{"China", "Thailand", "South Korea"}'),
('What is the largest organ in the human body?', 'Skin', '{"Liver", "Heart", "Lungs"}'),
('Which gas do plants absorb from the atmosphere?', 'Carbon Dioxide', '{"Oxygen", "Nitrogen", "Hydrogen"}'),
('What is the capital city of Spain?', 'Madrid', '{"Barcelona", "Valencia", "Seville"}'),
('Which ocean is the largest?', 'Pacific Ocean', '{"Atlantic Ocean", "Indian Ocean", "Arctic Ocean"}'),
('What is the primary ingredient in hummus?', 'Chickpeas', '{"Lentils", "Beans", "Peas"}'),
('Who painted the Starry Night?', 'Vincent van Gogh', '{"Pablo Picasso", "Claude Monet", "Leonardo da Vinci"}'),
('What is the most widely spoken language in the world?', 'Mandarin', '{"English", "Spanish", "Hindi"}'),
('In what year did World War II end?', '1945', '{"1944", "1946", "1939"}'),
('What is the capital of Australia?', 'Canberra', '{"Sydney", "Melbourne", "Brisbane"}'),
('What is the largest mammal in the world?', 'Blue Whale', '{"Elephant", "Giraffe", "Great White Shark"}'),
('Which planet is known as the Red Planet?', 'Mars', '{"Venus", "Jupiter", "Saturn"}'),
('Who wrote the play Romeo and Juliet?', 'William Shakespeare', '{"George Bernard Shaw", "Tennessee Williams", "Arthur Miller"}'),
('What is the hardest natural substance on Earth?', 'Diamond', '{"Gold", "Iron", "Graphite"}'),
('What is the capital of Canada?', 'Ottawa', '{"Toronto", "Vancouver", "Montreal"}'),
('What is the primary ingredient in a Caesar salad?', 'Romaine lettuce', '{"Iceberg lettuce", "Spinach", "Kale"}'),
('What year did the Titanic sink?', '1912', '{"1910", "1915", "1920"}'),
('Who was the first person to walk in space?', 'Alexei Leonov', '{"Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin"}'),
('Which is the largest continent?', 'Asia', '{"Africa", "North America", "South America"}'),
('What is the chemical symbol for gold?', 'Au', '{"Ag", "Pb", "Fe"}'),
('In which continent is the Sahara Desert located?', 'Africa', '{"Asia", "Australia", "South America"}'),
('What is the capital of Egypt?', 'Cairo', '{"Alexandria", "Giza", "Luxor"}'),
('What is the largest desert in the world?', 'Antarctica', '{"Sahara", "Gobi", "Kalahari"}'),
('What is the chemical symbol for iron?', 'Fe', '{"Ir", "I", "Al"}'),
('Which country is known for the kangaroo?', 'Australia', '{"New Zealand", "South Africa", "Canada"}'),
('What is the capital city of Italy?', 'Rome', '{"Venice", "Florence", "Milan"}'),
('Which planet is known as the Blue Planet?', 'Earth', '{"Mars", "Neptune", "Venus"}'),
('Who wrote "Pride and Prejudice"?', 'Jane Austen', '{"Charlotte Brontë", "Emily Brontë", "Mary Shelley"}'),
('What is the largest planet in our solar system?', 'Jupiter', '{"Saturn", "Earth", "Mars"}'),
('Who painted the ceiling of the Sistine Chapel?', 'Michelangelo', '{"Raphael", "Da Vinci", "Botticelli"}'),
('What is the main language spoken in Brazil?', 'Portuguese', '{"Spanish", "French", "English"}'),
('Who discovered penicillin?', 'Alexander Fleming', '{"Marie Curie", "Louis Pasteur", "Isaac Newton"}'),
('What is the capital of India?', 'New Delhi', '{"Mumbai", "Bangalore", "Kolkata"}'),
('Which gas is most abundant in the Earth’s atmosphere?', 'Nitrogen', '{"Oxygen", "Carbon Dioxide", "Argon"}'),
('What is the tallest mountain in the world?', 'Mount Everest', '{"K2", "Kilimanjaro", "Mont Blanc"}'),
('What is the currency of the United States?', 'Dollar', '{"Euro", "Pound", "Yen"}'),
('Which planet is known for its rings?', 'Saturn', '{"Jupiter", "Mars", "Neptune"}'),
('What is the capital of France?', 'Paris', '{"London", "Berlin", "Madrid"}'),
('Which element has the atomic number 1?', 'Hydrogen', '{"Helium", "Oxygen", "Carbon"}'),
('Who was the first woman to fly solo across the Atlantic Ocean?', 'Amelia Earhart', '{"Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"}'),
('What is the capital city of Germany?', 'Berlin', '{"Munich", "Frankfurt", "Hamburg"}'),
('What is the primary ingredient in guacamole?', 'Avocado', '{"Tomato", "Pepper", "Onion"}'),
('What is the longest river in the world?', 'Nile', '{"Amazon", "Yangtze", "Mississippi"}'),
('Who is known as the "Father of Geometry"?', 'Euclid', '{"Pythagoras", "Archimedes", "Galileo"}'),
('What is the main ingredient in sushi?', 'Rice', '{"Seaweed", "Fish", "Vegetables"}'),
('Which planet is closest to the Sun?', 'Mercury', '{"Venus", "Earth", "Mars"}'),
('What is the fastest land animal?', 'Cheetah', '{"Lion", "Horse", "Elephant"}'),
('What is the capital of Russia?', 'Moscow', '{"Saint Petersburg", "Kazakhstan", "Kyiv"}'),
('Who discovered gravity?', 'Isaac Newton', '{"Albert Einstein", "Galileo Galilei", "Nikola Tesla"}'),
('Which ocean is the Bermuda Triangle located in?', 'Atlantic Ocean', '{"Pacific Ocean", "Indian Ocean", "Arctic Ocean"}'),
('What is the chemical symbol for silver?', 'Ag', '{"Au", "Pb", "Cu"}'),
('Which planet has the most moons?', 'Saturn', '{"Jupiter", "Earth", "Mars"}'),
('What is the main ingredient in bread?', 'Flour', '{"Sugar", "Salt", "Water"}'),
('Who was the first president of the United States?', 'George Washington', '{"Thomas Jefferson", "Abraham Lincoln", "Franklin Roosevelt"}'),
('What is the capital of China?', 'Beijing', '{"Shanghai", "Hong Kong", "Tianjin"}'),
('Which element has the atomic number 8?', 'Oxygen', '{"Nitrogen", "Carbon", "Fluorine"}'),
('What is the longest river in South America?', 'Amazon River', '{"Nile River", "Yangtze River", "Mississippi River"}'),
('Which country is home to the pyramids?', 'Egypt', '{"Mexico", "Greece", "China"}'),
('What is the largest island in the world?', 'Greenland', '{"New Guinea", "Borneo", "Madagascar"}'),
('Who is the famous scientist known for the theory of relativity?', 'Albert Einstein', '{"Isaac Newton", "Galileo Galilei", "Stephen Hawking"}'),
('What is the primary ingredient in ketchup?', 'Tomato', '{"Sugar", "Vinegar", "Spices"}'),
('What is the capital city of South Korea?', 'Seoul', '{"Busan", "Incheon", "Gwangju"}'),
('Which animal is known as the King of the Jungle?', 'Lion', '{"Tiger", "Elephant", "Giraffe"}'),
('What is the capital of Italy?', 'Rome', '{"Venice", "Florence", "Milan"}'),
('Which ocean separates Africa from South America?', 'Atlantic Ocean', '{"Indian Ocean", "Pacific Ocean", "Arctic Ocean"}'),
('What is the official language of Brazil?', 'Portuguese', '{"Spanish", "English", "French"}'),
('What is the capital of Turkey?', 'Ankara', '{"Istanbul", "Izmir", "Bursa"}'),
('Which is the largest volcano in the world?', 'Mauna Loa', '{"Kilimanjaro", "Mount St. Helens", "Mount Fuji"}'),
('Who is known for the theory of evolution?', 'Charles Darwin', '{"Albert Einstein", "Isaac Newton", "Galileo Galilei"}'),
('What is the chemical formula for water?', 'H2O', '{"CO2", "O2", "H2"}'),
('Which is the smallest continent?', 'Australia', '{"Europe", "Antarctica", "South America"}'),
('What is the currency of Canada?', 'Canadian Dollar', '{"USD", "Euro", "Pound"}'),
('Who was the first female Prime Minister of the United Kingdom?', 'Margaret Thatcher', '{"Theresa May", "Angela Merkel", "Golda Meir"}'),
('What is the capital city of Greece?', 'Athens', '{"Thessaloniki", "Patras", "Heraklion"}'),
('What is the main ingredient in pesto sauce?', 'Basil', '{"Parsley", "Oregano", "Rosemary"}'),
('Which planet is known for its Great Red Spot?', 'Jupiter', '{"Mars", "Saturn", "Uranus"}'),
('What is the capital of Sweden?', 'Stockholm', '{"Oslo", "Helsinki", "Copenhagen"}'),
('What is the main ingredient in a traditional Scottish haggis?', 'Sheep offal', '{"Beef", "Pork", "Chicken"}'),
('Which is the longest mountain range in the world?', 'Andes', '{"Rocky Mountains", "Himalayas", "Alps"}'),
('What is the most populous country in the world?', 'China', '{"India", "USA", "Indonesia"}'),
('Who was the first man in space?', 'Yuri Gagarin', '{"Neil Armstrong", "Buzz Aldrin", "John Glenn"}'),
('What is the currency of India?', 'Rupee', '{"Dollar", "Yen", "Pound"}'),
('Which element has the chemical symbol "He"?', 'Helium', '{"Hydrogen", "Oxygen", "Carbon"}'),
('What is the capital city of Norway?', 'Oslo', '{"Stockholm", "Helsinki", "Copenhagen"}'),
('Which planet is farthest from the Sun?', 'Neptune', '{"Uranus", "Saturn", "Jupiter"}'),
('What is the largest type of deer?', 'Moose', '{"Elk", "Reindeer", "White-tailed Deer"}'),
('Who wrote "The Catcher in the Rye"?', 'J.D. Salinger', '{"Harper Lee", "F. Scott Fitzgerald", "Mark Twain"}'),
('What is the capital of Finland?', 'Helsinki', '{"Oslo", "Stockholm", "Copenhagen"}'),
('What is the only continent without a desert?', 'Europe', '{"Asia", "Africa", "Australia"}'),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', '{"Vincent van Gogh", "Pablo Picasso", "Claude Monet"}'),
('What is the capital of New Zealand?', 'Wellington', '{"Auckland", "Christchurch", "Hamilton"}'),
('Which famous scientist developed the three laws of motion?', 'Isaac Newton', '{"Albert Einstein", "Galileo Galilei", "Nikola Tesla"}'),
('What is the largest city in the United States?', 'New York City', '{"Los Angeles", "Chicago", "Houston"}'),
('Who wrote "The Great Gatsby"?', 'F. Scott Fitzgerald', '{"Ernest Hemingway", "Mark Twain", "John Steinbeck"}'),
('What is the currency of Russia?', 'Ruble', '{"Yuan", "Dollar", "Euro"}'),
('What is the capital city of Mexico?', 'Mexico City', '{"Guadalajara", "Monterrey", "Cancun"}'),
('Which animal is known for its ability to change colors?', 'Chameleon', '{"Lizard", "Frog", "Gecko"}'),
('What is the capital of Thailand?', 'Bangkok', '{"Chiang Mai", "Phuket", "Pattaya"}'),
('Who was the first woman to win a Nobel Prize?', 'Marie Curie', '{"Rosalind Franklin", "Jane Addams", "Malala Yousafzai"}'),
('What is the chemical symbol for sodium?', 'Na', '{"K", "Ca", "Mg"}'),
('What is the capital of Indonesia?', 'Jakarta', '{"Bali", "Surabaya", "Bandung"}'),
('Which planet is known for having the largest volcano?', 'Mars', '{"Earth", "Venus", "Jupiter"}'),
('What is the capital of Portugal?', 'Lisbon', '{"Porto", "Braga", "Coimbra"}'),
('Who invented the telephone?', 'Alexander Graham Bell', '{"Thomas Edison", "Nikola Tesla", "Graham Bell"}'),
('What is the capital of the Philippines?', 'Manila', '{"Cebu", "Davao", "Quezon City"}'),
('Which bird is known for its ability to mimic sounds?', 'Lyrebird', '{"Parrot", "Crow", "Sparrow"}'),
('What is the largest land animal?', 'Elephant', '{"Giraffe", "Hippopotamus", "Rhino"}'),
('Which country is known for its tulips?', 'Netherlands', '{"France", "Italy", "Germany"}'),
('What is the main ingredient in beer?', 'Barley', '{"Wheat", "Corn", "Rice"}'),
('What is the capital of Iceland?', 'Reykjavik', '{"Akureyri", "Kopavogur", "Selfoss"}'),
('Which fruit is known as the "king of fruits"?', 'Durian', '{"Mango", "Pineapple", "Banana"}'),
('What is the capital of Malaysia?', 'Kuala Lumpur', '{"Singapore", "Bangkok", "Jakarta"}'),
('Who discovered electricity?', 'Benjamin Franklin', '{"Thomas Edison", "Nikola Tesla", "Michael Faraday"}'),
('What is the capital of Bangladesh?', 'Dhaka', '{"Chittagong", "Khulna", "Sylhet"}'),
('What is the chemical symbol for potassium?', 'K', '{"P", "Na", "Ca"}'),
('Which country is famous for inventing pizza?', 'Italy', '{"Greece", "USA", "France"}'),
('What is the capital of Vietnam?', 'Hanoi', '{"Ho Chi Minh City", "Da Nang", "Nha Trang"}'),
('What is the largest mammal in the ocean?', 'Blue Whale', '{"Orca", "Great White Shark", "Dolphin"}'),
('Who wrote "Moby-Dick"?', 'Herman Melville', '{"Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald"}'),
('What is the capital of Chile?', 'Santiago', '{"Valparaíso", "Concepción", "La Serena"}'),
('What is the chemical formula for methane?', 'CH4', '{"C2H6", "CO2", "NH3"}'),
('What is the capital of Peru?', 'Lima', '{"Arequipa", "Cusco", "Trujillo"}'),
('Which country is famous for chocolate?', 'Switzerland', '{"Belgium", "France", "Germany"}'),
('What is the currency of South Africa?', 'Rand', '{"Dollar", "Pound", "Euro"}'),
('What is the capital city of Nigeria?', 'Abuja', '{"Lagos", "Port Harcourt", "Ibadan"}'),
('Who wrote "War and Peace"?', 'Leo Tolstoy', '{"Fyodor Dostoevsky", "Anton Chekhov", "Alexander Pushkin"}'),
('What is the capital of Argentina?', 'Buenos Aires', '{"Córdoba", "Rosario", "Mendoza"}'),
('What is the main ingredient in falafel?', 'Chickpeas', '{"Lentils", "Peas", "Beans"}'),
('What is the largest bone in the human body?', 'Femur', '{"Tibia", "Humerus", "Pelvis"}'),
('What is the currency of Egypt?', 'Egyptian Pound', '{"Dollar", "Euro", "Rupee"}'),
('What is the capital city of Iraq?', 'Baghdad', '{"Mosul", "Basra", "Erbil"}'),
('Which element has the chemical symbol "C"?', 'Carbon', '{"Calcium", "Copper", "Cobalt"}'),
('What is the largest species of shark?', 'Whale Shark', '{"Great White Shark", "Tiger Shark", "Hammerhead Shark"}'),
('What is the capital of Colombia?', 'Bogotá', '{"Medellín", "Cali", "Cartagena"}'),
('Who is the Greek god of the sea?', 'Poseidon', '{"Zeus", "Hades", "Apollo"}'),
('What is the capital city of Saudi Arabia?', 'Riyadh', '{"Jeddah", "Mecca", "Dammam"}'),
('What is the main ingredient in traditional Japanese miso soup?', 'Miso paste', '{"Soy sauce", "Tofu", "Seaweed"}'),
('What is the chemical formula for table salt?', 'NaCl', '{"KCl", "CaCl2", "LiCl"}'),
('What is the capital of Hungary?', 'Budapest', '{"Debrecen", "Szeged", "Pécs"}'),
('What is the largest species of penguin?', 'Emperor Penguin', '{"King Penguin", "Adélie Penguin", "Gentoo Penguin"}'),
('Who wrote "The Odyssey"?', 'Homer', '{"Virgil", "Sophocles", "Plato"}'),
('What is the capital of Ukraine?', 'Kyiv', '{"Odessa", "Lviv", "Kharkiv"}'),
('What is the chemical symbol for chlorine?', 'Cl', '{"C", "Br", "I"}'),
('Which continent is known as the "Dark Continent"?', 'Africa', '{"Asia", "South America", "Antarctica"}'),
('What is the capital of Kenya?', 'Nairobi', '{"Mombasa", "Kisumu", "Eldoret"}'),
('What is the primary ingredient in chocolate?', 'Cocoa beans', '{"Sugar", "Milk", "Vanilla"}'),
('Which country is home to the kangaroo?', 'Australia', '{"New Zealand", "South Africa", "India"}'),
('What is the capital of Libya?', 'Tripoli', '{"Benghazi", "Misrata", "Tobruk"}'),
('Who was the first African American president of the United States?', 'Barack Obama', '{"George Washington", "Abraham Lincoln", "Martin Luther King Jr."}'),
('What is the capital city of the United Arab Emirates?', 'Abu Dhabi', '{"Dubai", "Sharjah", "Ajman"}'),
('Which fruit is known for its high vitamin C content?', 'Orange', '{"Banana", "Apple", "Grapefruit"}'),
('What is the chemical symbol for nitrogen?', 'N', '{"O", "P", "S"}'),
('What is the capital of Jordan?', 'Amman', '{"Petra", "Irbid", "Zarqa"}'),
('Which planet has a day longer than its year?', 'Venus', '{"Mercury", "Mars", "Jupiter"}'),
('What is the largest city in Africa?', 'Lagos', '{"Cairo", "Kinshasa", "Nairobi"}'),
('Who wrote "The Iliad"?', 'Homer', '{"Virgil", "Dante", "Shakespeare"}'),
('What is the capital of Slovakia?', 'Bratislava', '{"Košice", "Prešov", "Nitra"}'),
('Which gas is essential for human respiration?', 'Oxygen', '{"Carbon Dioxide", "Nitrogen", "Hydrogen"}'),
('Who painted "The Last Supper"?', 'Leonardo da Vinci', '{"Michelangelo", "Raphael", "Caravaggio"}'),
('What is the capital city of Ethiopia?', 'Addis Ababa', '{"Nairobi", "Asmara", "Khartoum"}'),
('Which ocean is known for its coral reefs?', 'Pacific Ocean', '{"Atlantic Ocean", "Indian Ocean", "Arctic Ocean"}'),
('What is the capital of Tanzania?', 'Dodoma', '{"Dar es Salaam", "Arusha", "Zanzibar"}'),
('What is the largest type of cat?', 'Siberian Tiger', '{"Bengal Tiger", "African Lion", "Cougar"}'),
('Who wrote "Brave New World"?', 'Aldous Huxley', '{"George Orwell", "Ray Bradbury", "Margaret Atwood"}'),
('What is the capital of Cyprus?', 'Nicosia', '{"Limassol", "Famagusta", "Kyrenia"}'),
('Which animal is known as the "Ship of the Desert"?', 'Camel', '{"Horse", "Donkey", "Elephant"}'),
('What is the main ingredient in traditional sushi?', 'Rice', '{"Seaweed", "Fish", "Vegetables"}'),
('Who is the author of "1984"?', 'George Orwell', '{"Aldous Huxley", "Ray Bradbury", "F. Scott Fitzgerald"}'),
('What is the capital city of Armenia?', 'Yerevan', '{"Gyumri", "Vanadzor", "Artik"}'),
('What is the capital of Costa Rica?', 'San José', '{"Alajuela", "Cartago", "Heredia"}'),
('Which animal is known for its ability to fly backwards?', 'Hummingbird', '{"Sparrow", "Finch", "Robin"}'),
('What is the capital city of Kazakhstan?', 'Astana', '{"Almaty", "Shymkent", "Karaganda"}'),
('What is the largest type of bear?', 'Polar Bear', '{"Grizzly Bear", "Black Bear", "Kodiak Bear"}'),
('Who was the first woman to win a Nobel Prize in Physics?', 'Marie Curie', '{"Lise Meitner", "Rosalind Franklin", "Chien-Shiung Wu"}'),
('What is the capital of Belize?', 'Belmopan', '{"Belize City", "San Ignacio", "Orange Walk Town"}'),
('What is the chemical symbol for carbon dioxide?', 'CO2', '{"O2", "CH4", "H2O"}'),
('Which is the smallest bird in the world?', 'Bee Hummingbird', '{"Goldcrest", "Wren", "Chickadee"}'),
('What is the capital city of Bhutan?', 'Thimphu', '{"Paro", "Punakha", "Gelephu"}'),
('Who wrote "The Chronicles of Narnia"?', 'C.S. Lewis', '{"J.K. Rowling", "J.R.R. Tolkien", "Philip Pullman"}'),
('What is the largest city in China?', 'Shanghai', '{"Beijing", "Hong Kong", "Guangzhou"}'),
('Which country is known for its fjords?', 'Norway', '{"Sweden", "Finland", "Denmark"}'),
('What is the capital of Mongolia?', 'Ulaanbaatar', '{"Darkhan", "Erdenet", "Mörön"}'),
('What is the longest river in Europe?', 'Volga', '{"Danube", "Rhine", "Elbe"}'),
('What is the capital city of Latvia?', 'Riga', '{"Jūrmala", "Daugavpils", "Liepāja"}'),
('Who is the author of "The Picture of Dorian Gray"?', 'Oscar Wilde', '{"Charles Dickens", "Jane Austen", "Mark Twain"}'),
('What is the capital of Estonia?', 'Tallinn', '{"Tartu", "Narva", "Pärnu"}'),
('Which animal is known for its ability to regenerate limbs?', 'Axolotl', '{"Salamander", "Newt", "Frog"}'),
('What is the capital city of Lithuania?', 'Vilnius', '{"Kaunas", "Klaipėda", "Šiauliai"}'),
('Who painted "The Scream"?', 'Edvard Munch', '{"Pablo Picasso", "Vincent van Gogh", "Henri Matisse"}'),
('What is the capital of Slovakia?', 'Bratislava', '{"Kosice", "Nitra", "Prešov"}'),
('What is the most spoken language in Brazil?', 'Portuguese', '{"Spanish", "English", "French"}'),
('What is the capital city of Switzerland?', 'Bern', '{"Geneva", "Zurich", "Lausanne"}'),
('Which country is known for its windmills?', 'Netherlands', '{"Belgium", "Germany", "France"}'),
('What is the capital city of South Africa?', 'Pretoria', '{"Cape Town", "Johannesburg", "Durban"}'),
('What is the chemical formula for glucose?', 'C6H12O6', '{"C6H10O5", "C5H10O5", "C7H14O7"}'),
('What is the capital of Zimbabwe?', 'Harare', '{"Bulawayo", "Mutare", "Gweru"}'),
('Who is known as the "Father of Medicine"?', 'Hippocrates', '{"Galileo", "Aristotle", "Plato"}'),
('What is the capital city of Venezuela?', 'Caracas', '{"Maracaibo", "Valencia", "Barquisimeto"}'),
('What is the currency of Nigeria?', 'Naira', '{"Dollar", "Pound", "Euro"}'),
('What is the capital city of Peru?', 'Lima', '{"Arequipa", "Cusco", "Trujillo"}'),
('What is the main ingredient in a cheeseburger?', 'Cheese', '{"Bread", "Meat", "Lettuce"}'),
('What is the capital city of Barbados?', 'Bridgetown', '{"Speightstown", "Oistins", "Holetown"}'),
('What is the chemical symbol for lithium?', 'Li', '{"Na", "K", "Rb"}'),
('What is the capital of Cyprus?', 'Nicosia', '{"Limassol", "Famagusta", "Kyrenia"}'),
('What is the largest lake in Africa?', 'Lake Victoria', '{"Lake Tanganyika", "Lake Malawi", "Lake Albert"}'),
('Who wrote "The Old Man and the Sea"?', 'Ernest Hemingway', '{"F. Scott Fitzgerald", "Mark Twain", "John Steinbeck"}'),
('What is the capital of Malta?', 'Valletta', '{"Mdina", "Sliema", "Gozo"}'),
('What is the primary ingredient in a margarita?', 'Tequila', '{"Vodka", "Rum", "Whiskey"}'),
('What is the capital city of Fiji?', 'Suva', '{"Nadi", "Lautoka", "Labasa"}'),
('What is the capital city of Mongolia?', 'Ulaanbaatar', '{"Darkhan", "Erdenet", "Choibalsan"}'),
('What is the chemical symbol for calcium?', 'Ca', '{"C", "Cl", "Cr"}'),
('What is the largest desert in Asia?', 'Gobi Desert', '{"Thar Desert", "Arabian Desert", "Karakum Desert"}'),
('Who wrote "Les Misérables"?', 'Victor Hugo', '{"Charles Dickens", "Leo Tolstoy", "Gustave Flaubert"}'),
('What is the capital city of Nicaragua?', 'Managua', '{"León", "Granada", "Masaya"}'),
('What is the main ingredient in tofu?', 'Soybeans', '{"Peas", "Lentils", "Rice"}'),
('What is the capital of Samoa?', 'Apia', '{"Auckland", "Suva", "Honiara"}'),
('What is the capital city of the Maldives?', 'Malé', '{"Addu City", "Fuvahmulah", "Dhidhdhoo"}'),
('What is the currency of Japan?', 'Yen', '{"Won", "Dollar", "Euro"}'),
('What is the capital of Palau?', 'Ngerulmud', '{"Koror", "Melekeok", "Angaur"}'),
('What is the capital of the Solomon Islands?', 'Honiara', '{"Gizo", "Auki", "Nusatupe"}'),
('What is the largest city in Sri Lanka?', 'Colombo', '{"Kandy", "Galle", "Negombo"}'),
('What is the currency of Pakistan?', 'Pakistani Rupee', '{"Dollar", "Yen", "Rupee"}'),
('What is the capital of Micronesia?', 'Palikir', '{"Colonia", "Weno", "Yap"}'),
('Who is known as the "Father of Geometry"?', 'Euclid', '{"Archimedes", "Pythagoras", "Thales"}'),
('What is the capital of Tuvalu?', 'Funafuti', '{"Funafuti", "Fakaofo", "Nukufetau"}'),
('What is the main ingredient in guacamole?', 'Avocado', '{"Tomato", "Onion", "Garlic"}'),
('What is the capital of the Central African Republic?', 'Bangui', '{"Bangui", "Berberati", "Bimbo"}'),
('What is the capital of Angola?', 'Luanda', '{"Lobito", "Huambo", "Benguela"}'),
('What is the capital of Seychelles?', 'Victoria', '{"Mahé", "Praslin", "La Digue"}'),
('What is the capital of Kiribati?', 'Tarawa', '{"Kiritimati", "Banaba", "Abemama"}'),
('What is the capital of the Comoros?', 'Moroni', '{"Mitsamiouli", "Moutsamoudou", "Domoni"}'),
('What is the currency of the Maldives?', 'Maldivian Rufiyaa', '{"Dollar", "Yen", "Euro"}'),
('What is the capital of Suriname?', 'Paramaribo', '{"Domburg", "Brownsweg", "Nickerie"}'),
('What is the largest island in the Mediterranean Sea?', 'Sicily', '{"Sardinia", "Crete", "Cyprus"}'),
('What is the main ingredient in traditional Japanese ramen?', 'Noodles', '{"Rice", "Tofu", "Seaweed"}'),
('What is the capital of Samoa?', 'Apia', '{"Auckland", "Suva", "Honiara"}'),
('What is the capital city of Jamaica?', 'Kingston', '{"Montego Bay", "Mandeville", "Port Antonio"}'),
('What is the capital of Vanuatu?', 'Port Vila', '{"Luganville", "Tanna", "Espiritu Santo"}'),
('Who invented the printing press?', 'Johannes Gutenberg', '{"Thomas Edison", "Alexander Graham Bell", "Henry Ford"}'),
('What is the capital of St. Kitts and Nevis?', 'Basseterre', '{"Charlestown", "Cotton Ground", "Dieppe Bay Town"}'),
('What is the capital city of Dominica?', 'Roseau', '{"Portsmouth", "Marigot", "Wesley"}'),
('What is the capital city of Barbados?', 'Bridgetown', '{"Speightstown", "Oistins", "Holetown"}'),
('What is the capital city of Trinidad and Tobago?', 'Port of Spain', '{"San Fernando", "Scarborough", "Tobago"}'),
('What is the currency of the Bahamas?', 'Bahamian Dollar', '{"US Dollar", "Euro", "Pound"}'),
('What is the capital city of Belize?', 'Belmopan', '{"Belize City", "San Ignacio", "Orange Walk Town"}'),
('What is the capital of St. Vincent and the Grenadines?', 'Kingstown', '{"Bequia", "Union Island", "Mayreau"}'),
('What is the currency of Antigua and Barbuda?', 'East Caribbean Dollar', '{"US Dollar", "Pound", "Euro"}'),
('What is the capital of Guyana?', 'Georgetown', '{"Linden", "New Amsterdam", "Bartica"}'),
('What is the capital of Haiti?', 'Port-au-Prince', '{"Cap-Haïtien", "Les Cayes", "Jacmel"}'),
('What is the capital city of Saint Lucia?', 'Castries', '{"Vieux Fort", "Soufrière", "Gros Islet"}'),
('What is the currency of Jamaica?', 'Jamaican Dollar', '{"US Dollar", "Euro", "Pound"}'),
('What is the capital city of the Bahamas?', 'Nassau', '{"Freeport", "Marsh Harbour", "West End"}'),
('What is the capital of the Maldives?', 'Malé', '{"Addu City", "Fuvahmulah", "Dhidhdhoo"}'),
('What is the capital of Aruba?', 'Oranjestad', '{"San Nicolas", "Noord", "Santa Cruz"}'),
('What is the capital city of Dominica?', 'Roseau', '{"Portsmouth", "Marigot", "Wesley"}'),
('What is the currency of the Cayman Islands?', 'Cayman Islands Dollar', '{"US Dollar", "Euro", "Pound"}'),
('What is the currency of Saint Vincent and the Grenadines?', 'East Caribbean Dollar', '{"US Dollar", "Euro", "Pound"}'),
('What is the capital city of Saint Kitts and Nevis?', 'Basseterre', '{"Charlestown", "Cotton Ground", "Dieppe Bay Town"}'),
('What is the capital of Suriname?', 'Paramaribo', '{"Domburg", "Brownsweg", "Nickerie"}'),
('What is the capital city of the Turks and Caicos Islands?', 'Grand Turk', '{"North Caicos", "South Caicos", "Middle Caicos"}'),
('What is the capital of the British Virgin Islands?', 'Road Town', '{"Tortola", "Anegada", "Jost Van Dyke"}'),
('What is the capital of Anguilla?', 'The Valley', '{"Sandy Ground", "Blowing Point", "South Hill"}'),
('What is the capital of Montserrat?', 'Plymouth', '{"Brades", "Little Bay", "Derrick Hill"}'),
('What is the capital city of the Bahamas?', 'Nassau', '{"Freeport", "Marsh Harbour", "West End"}'),
('What is the capital of the Turks and Caicos Islands?', 'Grand Turk', '{"North Caicos", "South Caicos", "Middle Caicos"}'),
('What is the capital of the Falkland Islands?', 'Stanley', '{"Port Stanley", "Goose Green", "Darwin"}'),
('What is the capital city of the Virgin Islands?', 'Road Town', '{"Tortola", "Anegada", "Jost Van Dyke"}'),
('What is the capital of the Northern Mariana Islands?', 'Saipan', '{"Tinian", "Rota", "Guam"}'),
('What is the capital city of the American Samoa?', 'Pago Pago', '{"Fagatogo", "Aunu’u", "Ofu"}'),
('What is the capital of the U.S. Virgin Islands?', 'Charlotte Amalie', '{"Christiansted", "Frederiksted", "Hassel Island"}'),
('What is the capital of the British Indian Ocean Territory?', 'Diego Garcia', '{"Peros Banhos", "Salomon", "Bikini Atoll"}'),
('What is the capital of the United States Virgin Islands?', 'Charlotte Amalie', '{"Christiansted", "Frederiksted", "Hassel Island"}'),
('What is the currency of the British Virgin Islands?', 'United States Dollar', '{"Euro", "Pound", "East Caribbean Dollar"}'),
('What is the capital of Puerto Rico?', 'San Juan', '{"Bayamón", "Ponce", "Arecibo"}'),
('What is the capital city of the Cook Islands?', 'Avarua', '{"Rarotonga", "Mangaia", "Aitutaki"}'),
('What is the capital of Niue?', 'Alofi', '{"Hanan", "Tua Tika", "Matauranga"}'),
('What is the capital of Tokelau?', 'Nukunonu', '{"Atafu", "Fakaofo", "Ono-i-Lau"}'),
('What is the capital of Wallis and Futuna?', 'Mata-Utu', '{"Mata-Utu", "Alofi", "Uvea"}'),
('What is the capital of Christmas Island?', 'Flying Fish Cove', '{"Haven", "Sandy Point", "North West Point"}'),
('What is the capital of Cocos (Keeling) Islands?', 'West Island', '{"Henderson Island", "North Keeling Island", "Home Island"}'),
('What is the capital of the South Georgia and the South Sandwich Islands?', 'Grytviken', '{"King Edward Point", "Bird Island", "Coronation Island"}'),
('What is the capital of the Antarctic Peninsula?', 'None', '{"Palmer Station", "McMurdo Station", "Amundsen-Scott"}'),
('What is the capital of the French Southern and Antarctic Lands?', 'Port-aux-Français', '{"Fakarava", "Mataiva", "Nuku Hiva"}'),
('What is the capital city of the Australian Antarctic Territory?', 'None', '{"Macquarie Island", "Heard Island", "Kerguelen"}'),
('What is the capital of the British Antarctic Territory?', 'None', '{"Port Stanley", "Palmer Station", "McMurdo Station"}'),
('What is the capital of the Bouvet Island?', 'None', '{"Aukra", "Langholmen", "Bjordalsviken"}'),
('What is the capital of the Isle of Man?', 'Douglas', '{"Castletown", "Peel", "Ramsey"}'),
('What is the capital of the British Indian Ocean Territory?', 'Diego Garcia', '{"Peros Banhos", "Salomon", "Bikini Atoll"}'),
('What is the capital of the Cook Islands?', 'Avarua', '{"Rarotonga", "Mangaia", "Aitutaki"}'),
('What is the capital of Niue?', 'Alofi', '{"Hanan", "Tua Tika", "Matauranga"}'),
('What is the capital of the Vatican City?', 'Vatican City', '{"Rome", "Florence", "Venice"}'),
('What is the capital of Monaco?', 'Monaco', '{"Monte Carlo", "La Condamine", "Moneghetti"}'),
('What is the capital of San Marino?', 'San Marino', '{"Serravalle", "Borgo Maggiore", "City of San Marino"}'),
('What is the capital of Andorra?', 'Andorra la Vella', '{"Escaldes-Engordany", "Encamp", "La Massana"}'),
('What is the capital of Liechtenstein?', 'Vaduz', '{"Balzers", "Eschen", "Schaan"}'),
('What is the capital of Luxembourg?', 'Luxembourg City', '{"Esch-sur-Alzette", "Differdange", "Echternach"}'),
('What is the capital of Malta?', 'Valletta', '{"Mdina", "Sliema", "Gozo"}'),
('What is the capital of Portugal?', 'Lisbon', '{"Porto", "Braga", "Coimbra"}'),
('What is the capital of Spain?', 'Madrid', '{"Barcelona", "Sevilla", "Valencia"}'),
('What is the capital of Italy?', 'Rome', '{"Milan", "Naples", "Florence"}'),
('What is the capital of France?', 'Paris', '{"Lyon", "Marseille", "Nice"}'),
('What is the capital of Germany?', 'Berlin', '{"Munich", "Hamburg", "Frankfurt"}'),
('What is the capital of the Netherlands?', 'Amsterdam', '{"Rotterdam", "The Hague", "Utrecht"}'),
('What is the capital of Belgium?', 'Brussels', '{"Antwerp", "Ghent", "Bruges"}'),
('What is the capital of Switzerland?', 'Bern', '{"Geneva", "Zurich", "Lausanne"}'),
('What is the capital of Greece?', 'Athens', '{"Thessaloniki", "Patras", "Heraklion"}'),
('What is the capital of Sweden?', 'Stockholm', '{"Gothenburg", "Malmo", "Uppsala"}'),
('What is the capital of Norway?', 'Oslo', '{"Bergen", "Stavanger", "Trondheim"}'),
('What is the capital of Denmark?', 'Copenhagen', '{"Aarhus", "Odense", "Aalborg"}'),
('What is the capital of Finland?', 'Helsinki', '{"Espoo", "Vantaa", "Oulu"}'),
('What is the capital of Iceland?', 'Reykjavik', '{"Akureyri", "Kopavogur", "Selfoss"}'),
('What is the capital of Ireland?', 'Dublin', '{"Cork", "Limerick", "Galway"}'),
('What is the capital of the United Kingdom?', 'London', '{"Edinburgh", "Cardiff", "Belfast"}'),
('What is the capital of the United States?', 'Washington, D.C.', '{"New York City", "Los Angeles", "Chicago"}'),
('What is the capital of Canada?', 'Ottawa', '{"Toronto", "Vancouver", "Montreal"}'),
('What is the capital of Mexico?', 'Mexico City', '{"Guadalajara", "Monterrey", "Puebla"}'),
('What is the capital of Brazil?', 'Brasília', '{"Rio de Janeiro", "São Paulo", "Salvador"}'),
('What is the capital of Argentina?', 'Buenos Aires', '{"Córdoba", "Rosario", "Mendoza"}'),
('What is the capital of Chile?', 'Santiago', '{"Valparaíso", "Concepción", "La Serena"}'),
('What is the capital of Colombia?', 'Bogotá', '{"Medellín", "Cali", "Cartagena"}'),
('What is the capital of Peru?', 'Lima', '{"Arequipa", "Cusco", "Trujillo"}'),
('What is the capital of Venezuela?', 'Caracas', '{"Maracaibo", "Valencia", "Barquisimeto"}'),
('What is the capital of Uruguay?', 'Montevideo', '{"Salto", "Paysandú", "Tacuarembó"}'),
('What is the capital of Paraguay?', 'Asunción', '{"Ciudad del Este", "Encarnación", "Concepción"}'),
('What is the capital of Bolivia?', 'Sucre', '{"La Paz", "Cochabamba", "Santa Cruz"}'),
('What is the capital of Ecuador?', 'Quito', '{"Guayaquil", "Cuenca", "Machala"}'),
('What is the capital of Guyana?', 'Georgetown', '{"Linden", "New Amsterdam", "Bartica"}'),
('What is the capital of Suriname?', 'Paramaribo', '{"Domburg", "Brownsweg", "Nickerie"}'),
('What is the capital of French Guiana?', 'Cayenne', '{"Kourou", "Remire-Montjoly", "Saint-Laurent-du-Maroni"}'),
('What is the capital of the Bahamas?', 'Nassau', '{"Freeport", "Marsh Harbour", "West End"}'),
('What is the capital of Jamaica?', 'Kingston', '{"Montego Bay", "Mandeville", "Port Antonio"}'),
('What is the capital of Barbados?', 'Bridgetown', '{"Speightstown", "Oistins", "Holetown"}'),
('What is the capital of Trinidad and Tobago?', 'Port of Spain', '{"San Fernando", "Scarborough", "Tobago"}'),
('What is the capital of Saint Lucia?', 'Castries', '{"Vieux Fort", "Soufrière", "Gros Islet"}'),
('What is the capital of Saint Vincent and the Grenadines?', 'Kingstown', '{"Bequia", "Union Island", "Mayreau"}'),
('What is the capital of Saint Kitts and Nevis?', 'Basseterre', '{"Charlestown", "Cotton Ground", "Dieppe Bay Town"}'),
('What is the capital of Dominica?', 'Roseau', '{"Portsmouth", "Marigot", "Wesley"}'),
('What is the capital of Puerto Rico?', 'San Juan', '{"Bayamón", "Ponce", "Arecibo"}'),
('What is the capital of the Virgin Islands?', 'Road Town', '{"Tortola", "Anegada", "Jost Van Dyke"}'),
('What is the capital of the United States Virgin Islands?', 'Charlotte Amalie', '{"Christiansted", "Frederiksted", "Hassel Island"}'),
('What is the capital of the Falkland Islands?', 'Stanley', '{"Port Stanley", "Goose Green", "Darwin"}'),
('What is the capital of Gibraltar?', 'Gibraltar', '{"La Linea de la Concepcion", "Algeciras", "Tarifa"}'),
('What is the capital of the British Indian Ocean Territory?', 'Diego Garcia', '{"Peros Banhos", "Salomon", "Bikini Atoll"}'),
('What is the capital of the South Georgia and the South Sandwich Islands?', 'Grytviken', '{"King Edward Point", "Bird Island", "Coronation Island"}'),
('What is the capital of the Australian Antarctic Territory?', 'None', '{"Macquarie Island", "Heard Island", "Kerguelen"}'),
('What is the capital of the British Antarctic Territory?', 'None', '{"Port Stanley", "Palmer Station", "McMurdo Station"}'),
('What is the capital of the Bouvet Island?', 'None', '{"Aukra", "Langholmen", "Bjordalsviken"}'),
('What is the capital of the Isle of Man?', 'Douglas', '{"Castletown", "Peel", "Ramsey"}'),
('What is the capital of Malta?', 'Valletta', '{"Mdina", "Sliema", "Gozo"}'),
('What is the capital of Luxembourg?', 'Luxembourg City', '{"Esch-sur-Alzette", "Differdange", "Echternach"}'),
('What is the capital of Monaco?', 'Monaco', '{"Monte Carlo", "La Condamine", "Moneghetti"}'),
('What is the capital of San Marino?', 'San Marino', '{"Serravalle", "Borgo Maggiore", "City of San Marino"}'),
('What is the capital of Andorra?', 'Andorra la Vella', '{"Escaldes-Engordany", "Encamp", "La Massana"}'),
('What is the capital of Liechtenstein?', 'Vaduz', '{"Balzers", "Eschen", "Schaan"}'),
('What is the capital of Vatican City?', 'Vatican City', '{"Rome", "Florence", "Venice"}'),
('What is the capital of Switzerland?', 'Bern', '{"Geneva", "Zurich", "Lausanne"}'),
('What is the capital of Greece?', 'Athens', '{"Thessaloniki", "Patras", "Heraklion"}'),
('What is the capital of Sweden?', 'Stockholm', '{"Gothenburg", "Malmo", "Uppsala"}'),
('What is the capital of Norway?', 'Oslo', '{"Bergen", "Stavanger", "Trondheim"}'),
('What is the capital of Denmark?', 'Copenhagen', '{"Aarhus", "Odense", "Aalborg"}'),
('What is the capital of Finland?', 'Helsinki', '{"Espoo", "Vantaa", "Oulu"}'),
('What is the capital of Iceland?', 'Reykjavik', '{"Akureyri", "Kopavogur", "Selfoss"}'),
('What is the capital of Ireland?', 'Dublin', '{"Cork", "Limerick", "Galway"}'),
('What is the capital of the United Kingdom?', 'London', '{"Edinburgh", "Cardiff", "Belfast"}'),
('What is the capital of the United States?', 'Washington, D.C.', '{"New York City", "Los Angeles", "Chicago"}'),
('What is the capital of Canada?', 'Ottawa', '{"Toronto", "Vancouver", "Montreal"}'),
('What is the capital of Mexico?', 'Mexico City', '{"Guadalajara", "Monterrey", "Puebla"}'),
('What is the capital of Brazil?', 'Brasília', '{"Rio de Janeiro", "São Paulo", "Salvador"}'),
('What is the capital of Argentina?', 'Buenos Aires', '{"Córdoba", "Rosario", "Mendoza"}'),
('What is the capital of Chile?', 'Santiago', '{"Valparaíso", "Concepción", "La Serena"}'),
('What is the capital of Colombia?', 'Bogotá', '{"Medellín", "Cali", "Cartagena"}'),
('What is the capital of Peru?', 'Lima', '{"Arequipa", "Cusco", "Trujillo"}'),
('What is the capital of Venezuela?', 'Caracas', '{"Maracaibo", "Valencia", "Barquisimeto"}'),
('What is the capital of Uruguay?', 'Montevideo', '{"Salto", "Paysandú", "Tacuarembó"}'),
('What is the capital of Paraguay?', 'Asunción', '{"Ciudad del Este", "Encarnación", "Concepción"}'),
('What is the capital of Bolivia?', 'Sucre', '{"La Paz", "Cochabamba", "Santa Cruz"}'),
('What is the capital of Ecuador?', 'Quito', '{"Guayaquil", "Cuenca", "Machala"}'),
('What is the capital of Guyana?', 'Georgetown', '{"Linden", "New Amsterdam", "Bartica"}'),
('What is the capital of Suriname?', 'Paramaribo', '{"Domburg", "Brownsweg", "Nickerie"}'),
('What is the capital of French Guiana?', 'Cayenne', '{"Kourou", "Remire-Montjoly", "Saint-Laurent-du-Maroni"}'),
('What is the capital of the Bahamas?', 'Nassau', '{"Freeport", "Marsh Harbour", "West End"}'),
('What is the capital of Jamaica?', 'Kingston', '{"Montego Bay", "Mandeville", "Port Antonio"}'),
('What is the capital of Barbados?', 'Bridgetown', '{"Speightstown", "Oistins", "Holetown"}'),
('What is the capital of Trinidad and Tobago?', 'Port of Spain', '{"San Fernando", "Scarborough", "Tobago"}'),
('What is the capital of Saint Lucia?', 'Castries', '{"Vieux Fort", "Soufrière", "Gros Islet"}'),
('What is the capital of Saint Vincent and the Grenadines?', 'Kingstown', '{"Bequia", "Union Island", "Mayreau"}'),
('What is the capital of Saint Kitts and Nevis?', 'Basseterre', '{"Charlestown", "Cotton Ground", "Dieppe Bay Town"}'),
('What is the capital of Dominica?', 'Roseau', '{"Portsmouth", "Marigot", "Wesley"}'),
('What is the capital of Puerto Rico?', 'San Juan', '{"Bayamón", "Ponce", "Arecibo"}'),
('What is the capital of the Virgin Islands?', 'Road Town', '{"Tortola", "Anegada", "Jost Van Dyke"}'),
('What is the capital of the United States Virgin Islands?', 'Charlotte Amalie', '{"Christiansted", "Frederiksted", "Hassel Island"}'),
('What is the capital of the Falkland Islands?', 'Stanley', '{"Port Stanley", "Goose Green", "Darwin"}'),
('What is the capital of Gibraltar?', 'Gibraltar', '{"La Linea de la Concepcion", "Algeciras", "Tarifa"}'),
('What is the capital of the British Indian Ocean Territory?', 'Diego Garcia', '{"Peros Banhos", "Salomon", "Bikini Atoll"}'),
('What is the capital of the South Georgia and the South Sandwich Islands?', 'Grytviken', '{"King Edward Point", "Bird Island", "Coronation Island"}'),
('What is the capital of the Australian Antarctic Territory?', 'None', '{"Macquarie Island", "Heard Island", "Kerguelen"}'),
('What is the capital of the British Antarctic Territory?', 'None', '{"Port Stanley", "Palmer Station", "McMurdo Station"}'),
('What is the capital of the Bouvet Island?', 'None', '{"Aukra", "Langholmen", "Bjordalsviken"}'),
('What is the capital of the Isle of Man?', 'Douglas', '{"Castletown", "Peel", "Ramsey"}'),
('What is the capital of Malta?', 'Valletta', '{"Mdina", "Sliema", "Gozo"}'),
('What is the capital of Luxembourg?', 'Luxembourg City', '{"Esch-sur-Alzette", "Differdange", "Echternach"}'),
('What is the capital of Monaco?', 'Monaco', '{"Monte Carlo", "La Condamine", "Moneghetti"}'),
('What is the capital of San Marino?', 'San Marino', '{"Serravalle", "Borgo Maggiore", "City of San Marino"}'),
('What is the capital of Andorra?', 'Andorra la Vella', '{"Escaldes-Engordany", "Encamp", "La Massana"}'),
('What is the capital of Liechtenstein?', 'Vaduz', '{"Balzers", "Eschen", "Schaan"}'),
('What is the capital of Vatican City?', 'Vatican City', '{"Rome", "Florence", "Venice"}'),
('What is the capital of Switzerland?', 'Bern', '{"Geneva", "Zurich", "Lausanne"}'),
('What is the capital of Greece?', 'Athens', '{"Thessaloniki", "Patras", "Heraklion"}'),
('What is the capital of Sweden?', 'Stockholm', '{"Gothenburg", "Malmo", "Uppsala"}'),
('What is the capital of Norway?', 'Oslo', '{"Bergen", "Stavanger", "Trondheim"}'),
('What is the capital of Denmark?', 'Copenhagen', '{"Aarhus", "Odense", "Aalborg"}'),
('What is the capital of Finland?', 'Helsinki', '{"Espoo", "Vantaa", "Oulu"}'),
('What is the capital of Iceland?', 'Reykjavik', '{"Akureyri", "Kopavogur", "Selfoss"}'),
('What is the capital of Ireland?', 'Dublin', '{"Cork", "Limerick", "Galway"}'),
('What is the capital of the United Kingdom?', 'London', '{"Edinburgh", "Cardiff", "Belfast"}'),
('What is the capital of the United States?', 'Washington, D.C.', '{"New York City", "Los Angeles", "Chicago"}'),
('What is the capital of Canada?', 'Ottawa', '{"Toronto", "Vancouver", "Montreal"}'),
('What is the capital of Mexico?', 'Mexico City', '{"Guadalajara", "Monterrey", "Puebla"}'),
('What is the capital of Brazil?', 'Brasília', '{"Rio de Janeiro", "São Paulo", "Salvador"}'),
('What is the capital of Argentina?', 'Buenos Aires', '{"Córdoba", "Rosario", "Mendoza"}'),
('What is the capital of Chile?', 'Santiago', '{"Valparaíso", "Concepción", "La Serena"}'),
('What is the capital of Colombia?', 'Bogotá', '{"Medellín", "Cali", "Cartagena"}'),
('What is the capital of Peru?', 'Lima', '{"Arequipa", "Cusco", "Trujillo"}'),
('What is the capital of Venezuela?', 'Caracas', '{"Maracaibo", "Valencia", "Barquisimeto"}'),
('What is the capital of Uruguay?', 'Montevideo', '{"Salto", "Paysandú", "Tacuarembó"}'),
('What is the capital of Paraguay?', 'Asunción', '{"Ciudad del Este", "Encarnación", "Concepción"}'),
('What is the capital of Bolivia?', 'Sucre', '{"La Paz", "Cochabamba", "Santa Cruz"}'),
('What is the capital of Ecuador?', 'Quito', '{"Guayaquil", "Cuenca", "Machala"}'),
('What is the capital of Guyana?', 'Georgetown', '{"Linden", "New Amsterdam", "Bartica"}'),
('What is the capital of Suriname?', 'Paramaribo', '{"Domburg", "Brownsweg", "Nickerie"}'),
('What is the capital of French Guiana?', 'Cayenne', '{"Kourou", "Remire-Montjoly", "Saint-Laurent-du-Maroni"}'),
('What is the capital of the Bahamas?', 'Nassau', '{"Freeport", "Marsh Harbour", "West End"}'),
('What is the capital of Jamaica?', 'Kingston', '{"Montego Bay", "Mandeville", "Port Antonio"}'),
('What is the capital of Barbados?', 'Bridgetown', '{"Speightstown", "Oistins", "Holetown"}'),
('What is the capital of Trinidad and Tobago?', 'Port of Spain', '{"San Fernando", "Scarborough", "Tobago"}'),
('What is the capital of Saint Lucia?', 'Castries', '{"Vieux Fort", "Soufrière", "Gros Islet"}'),
('What is the capital of Saint Vincent and the Grenadines?', 'Kingstown', '{"Bequia", "Union Island", "Mayreau"}'),
('What is the capital of Saint Kitts and Nevis?', 'Basseterre', '{"Charlestown", "Cotton Ground", "Dieppe Bay Town"}'),
('What is the capital of Dominica?', 'Roseau', '{"Portsmouth", "Marigot", "Wesley"}'),
('What is the capital of Puerto Rico?', 'San Juan', '{"Bayamón", "Ponce", "Arecibo"}'),
('What is the capital of the Virgin Islands?', 'Road Town', '{"Tortola", "Anegada", "Jost Van Dyke"}'),
('What is the capital of the United States Virgin Islands?', 'Charlotte Amalie', '{"Christiansted", "Frederiksted", "Hassel Island"}');  
